randomSignal = 200*rand(200,1);
figure(1);
plot(randomSignal);
title('Original Signal');
axis([0 200 -1000 1500]);
randomNoise=wgn(200,1,50);
 figure(2);
% plot(randomNoise);
signalPlusNoise=randomSignal+randomNoise;
%figure(3);
%plot(signalPlusNoise);
title('Signal plus Noise');
%figure(4);
%plot(abs(fft(randomSignal)));
title('fft of Orginal Signal');
%figure(5);
%plot(abs(fft(randomNoise)));
title('fft of Noise Signal');
%figure(6);
%plot(abs(fft(randomSignal)+fft(randomNoise)));
title('Addition of FFT Signal + FFT Noise');
%figure(7);
plot(abs(fft(signalPlusNoise)));
title('fft of SignalplusNoise Signal'); 
t=-100:1:99;
y=heaviside(t);
figure(8);
plot(y,t);
result=abs(fft(signalPlusNoise))*y;
plot(ifft(result));